BeatLab/Models/Entities/Feedback.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID_Feedback { get; set; }
        public System.DateTime Date_Comment { get; set; }
        public string Comment { get; set; }
        public int ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}

BeatLab/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeatLab.Models.Entities;

namespace BeatLab.Controllers
{
    public class FeedbacksController : Controller
    {
        private BeatLabDBEntities db = new BeatLabDBEntities();

        // GET: Feedbacks
        public ActionResult Index()
        {
            var feedback = db.Feedback.Include(f => f.User);
            return View(feedback.ToList());
        }

        // GET: Feedbacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // GET: Feedbacks/Create
        public ActionResult Create()
        {
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Last_Name_User");
            return View();
        }

        // POST: Feedbacks/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Feedback,Comment,ID_User")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Feedback.Add(feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Last_Name_User", feedback.ID_User);
            return View(feedback);
        }

        // GET: Feedbacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Last_Name_User", feedback.ID_User);
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Feedback,Comment,ID_User")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Last_Name_User", feedback.ID_User);
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Feedback feedback = db.Feedback.Find(id);
            db.Feedback.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult PostComment( string comment)
        {
            Feedback newComment = new Feedback
            {
             
                Date_Comment = DateTime.Now,
                Comment = comment,
                ID_User = db.User.First(u => u.Login == HttpContext.User.Identity.Name).ID_User
            };
            db.Feedback.Add(newComment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeatLab/Views/Feedbacks/Create.cshtml
@model BeatLab.Models.Entities.Feedback

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Feedback</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_User, "ID_User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_User", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_User, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BeatLab/Views/Feedbacks/Delete.cshtml
@model BeatLab.Models.Entities.Feedback

@{
    ViewBag.Title = "Удаление комментария";
}



<h3>Вы точно хотите удалить данный комментарий?</h3>
<div>

    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться", "Index","",new {@class = "btn btn-default" })
        </div>
    }
</div>

BeatLab/Views/Feedbacks/Details.cshtml
@model BeatLab.Models.Entities.Feedback

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Feedback</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Last_Name_User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Last_Name_User)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Feedback }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BeatLab/Views/Feedbacks/Edit.cshtml
@model BeatLab.Models.Entities.Feedback

@{
    ViewBag.Title = "Редактирование комментария";
}
<br />
<h2>Редактирование комментария</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Feedback)

    <div class="form-group">
        <label for="name-4c18" class="control-label col-md-2">Комментарий</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label for="name-4c18" class="control-label col-md-2">Пользователь</label>
        <div class="col-md-10">
            @Html.DropDownList("ID_User", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_User, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

BeatLab/Views/Feedbacks/Index.cshtml
@model IEnumerable<BeatLab.Models.Entities.Feedback>

@{
    ViewBag.Title = "Обратная связь";
}

<br />
<br />
<br />
<div>
    <h3 style="margin-left:15px;">Обратная связь</h3>

</div>




<section class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="panel">
                <div class="panel-body">
                    @using (Html.BeginForm("PostComment", "Feedbacks", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        <textarea name="comment" class="form-control" rows="2" style="height:80px;" placeholder="Добавьте Ваш комментарий"></textarea>
                        
                        <div class="mar-top clearfix">
                            <button class="btn btn-sm btn-primary pull-left" type="submit"><i class="fa fa-pencil fa-fw"></i> Добавить</button>
                        </div>


                    }
                    <br />
                    <br />
                    <br />
                </div>
            </div>
            <div class="panel">
                <div class="panel-body">
                    @foreach (var item in Model)
                    {
                        <div class="media-block">
                            <a class="media-left" href="#">
                                @{ if (item.User.Image_User == null)
                                    {
                                        <img id='previewImage' class="img-circle img-sm" alt="Профиль пользователя" src="~/Resource/user.png" />
                                    }
                                    else
                                    {
                                        @Html.Raw("<img id='previewImage' class='img-circle img-sm'  alt='Профиль пользователя' src=\"data:image/jpeg;base64,"
                                              + Convert.ToBase64String(item.User.Image_User) + "\" />")

                                    }
                                }

                            </a>
                            <div class="media-body">
                                <div class="mar-btm">
                                    <a href="#" class="btn-link text-semibold media-heading box-inline"> @(item.User.Nickname_User)</a>
                                    <p class="text-muted text-sm"><i class="fa fa-globe fa-lg"></i> - @(item.Date_Comment.Day).@(item.Date_Comment.Month).@(item.Date_Comment.Year)</p>
                                </div>
                                <p>@(item.Comment)</p>
                                @{
                                    if (User.IsInRole("admin"))
                                    {
                                        @Html.ActionLink("Редактировать", "Edit", "Feedbacks", new { id = item.ID_Feedback }, new { @class = "btn btn-default " })
                                        @Html.ActionLink("Удалить", "Delete", "Feedbacks", new { id = item.ID_Feedback }, new { @class = "btn btn-default " })
                                        }
                                    }
                                        <hr>

                                    </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div><!-- /.row -->
</section><!-- /.container -->