BeatLab/Models/Entities/Music.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Music()
        {
            this.Comment_Music = new HashSet<Comment_Music>();
            this.Order_Music = new HashSet<Order_Music>();
            this.Price_Music = new HashSet<Price_Music>();
        }
    
        public int ID_Music { get; set; }
        public Nullable<int> ID_Genere_of_Music { get; set; }
        public int ID_Type_mysic { get; set; }
        public string Name_music { get; set; }
        public string Description_Music { get; set; }
        public Nullable<int> ID_Alboms { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Music_file { get; set; }
        public byte[] Image_music { get; set; }
        public int ID_User { get; set; }
    
        public virtual Alboms Alboms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Music> Comment_Music { get; set; }
        public virtual Genere_Of_Music Genere_Of_Music { get; set; }
        public virtual Type_Music Type_Music { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Music> Order_Music { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Music> Price_Music { get; set; }
    }
}

BeatLab/Controllers/MusicsController.cs
using BeatLab.Models.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


namespace BeatLab.Controllers
{
    public class MusicsController : Controller
    {
        private readonly BeatLabDBEntities db = new BeatLabDBEntities();

        // GET: Musics
        [Authorize]
        public ActionResult Index()
        {
            LoadDropDownLists();
            var music = db.Music
                .Where(m => !m.IsDeleted)
                .Include(m => m.Alboms)
                .Include(m => m.Genere_Of_Music)
                .Include(m => m.Type_Music)
                .Include(m => m.User);
            return View(music.ToList());
        }

        private void LoadDropDownLists()
        {
            List<Genere_Of_Music> genres = db.Genere_Of_Music.ToList();
            genres.Insert(0, new Genere_Of_Music { Name_Gener_of_music = "-----" });
            ViewBag.ID_Genere_of_Music = new SelectList(genres, "ID_Genere_Of_Music", "Name_Gener_of_music");

            List<Type_Music> types = db.Type_Music.ToList();
            types.Insert(0, new Type_Music { Name_Type_Music = "-----" });
            ViewBag.ID_Type_mysic = new SelectList(types, "ID_Type_music", "Name_Type_Music");

            List<User> users = db.User.ToList().Where(u => u.User_Type.Name_User_Type == "user" && u.ID_User != Me.GetId()).ToList();
            users.Insert(0, new User { Nickname_User = "-----" });
            ViewBag.ID_User = new SelectList(users, "ID_User", "Nickname_User");
        }

        // GET: Musics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // GET: Musics/Create
        public ActionResult Create()
        {
            ViewBag.ID_Alboms = new SelectList(Me.User.Alboms, "ID_Album", "Name_Album");
            ViewBag.ID_Genere_of_Music = new SelectList(db.Genere_Of_Music, "ID_Genere_Of_Music", "Name_Gener_of_music");
            ViewBag.ID_Type_mysic = new SelectList(db.Type_Music, "ID_Type_music", "Name_Type_Music");
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Nickname_User");
            return View();
        }

        // POST: Musics/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Music,ID_Genere_of_Music,ID_Type_mysic,Name_music,Description_Music,Price_Music,ID_Alboms,Image_music,ID_User,PriceString,IsLicenseAgreementAccepted")] Music music, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                if (music.Name_music == null || music.Name_music == "")
                {
                    ModelState.AddModelError(nameof(music.Name_music), "Введите название");
                }
                if (music.Description_Music == null || music.Description_Music == "")
                {
                    ModelState.AddModelError(nameof(music.Description_Music), "Введите описание");
                }
            }


            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    music.Image_music = uploadImage.ToByteArray();
                }
                if (Request.Files["uploadMusic"] != null)
                {
                    music.Music_file = Request.Files["uploadMusic"].ToByteArray();
                }


                music.ID_User = db.User.First(u => u.Login == HttpContext.User.Identity.Name).ID_User;
                Price_Music priceMusic = new Price_Music
                {
                    Price = int.Parse(Request.Form["PriceString"]),
                    Date = DateTime.Now
                };
                music.Price_Music.Add(priceMusic);
                db.Music.Add(music);
                db.SaveChanges();
                return RedirectToAction("Details", "Users");
            }


            ViewBag.ID_Genere_of_Music = new SelectList(db.Genere_Of_Music, "ID_Genere_Of_Music", "Name_Gener_of_music", music.ID_Genere_of_Music);
            ViewBag.ID_Type_mysic = new SelectList(db.Type_Music, "ID_Type_music", "Name_Type_Music", music.ID_Type_mysic);

            return View(music);
        }

        // GET: Musics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }

            music.IsLicenseAgreementAccepted = true;
            music.PriceString = db.Price_Music
                .ToList()
                .Last().Price
                .ToString();

            ViewBag.ID_Alboms = new SelectList(Me.User.Alboms, "ID_Album", "Name_Album", music.ID_Alboms);
            ViewBag.ID_Genere_of_Music = new SelectList(db.Genere_Of_Music, "ID_Genere_Of_Music", "Name_Gener_of_music", music.ID_Genere_of_Music);
            ViewBag.ID_Type_mysic = new SelectList(db.Type_Music, "ID_Type_music", "Name_Type_Music", music.ID_Type_mysic);
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Nickname_User", music.ID_User);
            return View(music);
        }

        // POST: Musics/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Music,ID_Genere_of_Music,ID_Type_mysic,Name_music,Description_Music,Price_Music,ID_Alboms,Image_music,ID_User,PriceString,Music_file,IsLicenseAgreementAccepted")] Music music, HttpPostedFileBase uploadImage, HttpPostedFileBase uploadMusic)
        {
            music.IsLicenseAgreementAccepted = true;
            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    music.Image_music = uploadImage.ToByteArray();
                }
                if (uploadMusic != null)
                {
                    music.Music_file = uploadMusic.ToByteArray();
                }

                db.Entry(music).State = EntityState.Modified;
                db.SaveChanges();

                Price_Music priceMusic = new Price_Music
                {
                    ID_Music = music.ID_Music,
                    Price = int.Parse(music.PriceString),
                    Date = DateTime.Now
                };
                db.Price_Music.Add(priceMusic);
                db.SaveChanges();
                return RedirectToAction("Details", "Users");
            }
            ViewBag.ID_Alboms = new SelectList(db.Alboms, "ID_Album", "Name_Album", music.ID_Alboms);
            ViewBag.ID_Genere_of_Music = new SelectList(db.Genere_Of_Music, "ID_Genere_Of_Music", "Name_Gener_of_music", music.ID_Genere_of_Music);
            ViewBag.ID_Type_mysic = new SelectList(db.Type_Music, "ID_Type_music", "Name_Type_Music", music.ID_Type_mysic);
            ViewBag.ID_User = new SelectList(db.User, "ID_User", "Nickname_User", music.ID_User);
            return View(music);
        }

        // GET: Musics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = db.Music.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Musics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Music music = db.Music.Find(id);
            music.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Details", "Users");
        }


        public ActionResult LoadAudio(int musicId)
        {
            byte[] songBytes;
            songBytes = db.Music.First(m => m.ID_Music == musicId).Music_file;
            if (songBytes == null) return null;
            FileStreamResult songStreamResult =
                new FileStreamResult(new MemoryStream(songBytes),
                                     "audio/mp3");
            return songStreamResult;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult Filter()
        {
            List<Music> filteredMusics = db.Music
                .Where(m => !m.IsDeleted)
                .Include(m => m.Alboms)
                .Include(m => m.Genere_Of_Music)
                .Include(m => m.Type_Music)
                .Include(m => m.User)
                .ToList();
            if (!string.IsNullOrWhiteSpace(Request["Name"]))
            {
                filteredMusics = filteredMusics.Where(m =>
                {
                    return m.Name_music.IndexOf(Request["Name"],
                                                StringComparison.OrdinalIgnoreCase) != -1;
                })
                    .ToList();

BeatLab/Controllers/СhatController.cs
using BeatLab.Models.Entities;
using System.Linq;
using System.Web.Mvc;

namespace BeatLab.Controllers
{
    public class ChatController : Controller
    {
        private readonly BeatLabDBEntities db = new BeatLabDBEntities();

        // GET: Chat
        [Authorize]
        public ActionResult Index(int? inputReceiverId)
        {
            int receiverId;
            if (!inputReceiverId.HasValue)
            {
                receiverId = db.User
                    .Where(u => u.Login != HttpContext.User.Identity.Name)
                    .First().ID_User;
            }
            else
            {
                receiverId = db.User.Find(inputReceiverId).ID_User;
            }
            int senderId = db.User.FirstOrDefault(u => u.Login == HttpContext.User.Identity.Name)?.ID_User ?? 0;
            if (senderId == 0)
            {
                return RedirectToAction("Register", "Account");
            }
            ViewBag.Chat = db.Chat.Where(c => c.ID_Sender == senderId
                                              && c.ID_Receiver == receiverId
                                              || c.ID_Sender == receiverId
                                              && c.ID_Receiver == senderId);
            ViewBag.ReceiverId = receiverId;
            return View(db);
        }

        [HttpPost]
        public ActionResult PostComment(string text, int receiverId, int senderId)
        {
            if (!string.IsNullOrWhiteSpace(text))
            {
                Chat chat = new Chat
                {
                    ID_Receiver = receiverId,
                    ID_Sender = senderId,
                    Message = text
                };
                db.Chat.Add(chat);
                db.SaveChanges();
            }
            return RedirectToAction("Index", new { inputReceiverId = receiverId });
        }
    }
}

BeatLab/Views/Musics/Create.cshtml
@model BeatLab.Models.Entities.Music

@{
    @Styles.Render("~/Content/StylePage/AccountEditStyle.css")
    ViewBag.Title = "Добавить бит или семпл";
}


@using (Html.BeginForm(Html.BeginForm("Create", "Musics", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <h2 class="h2--margin">Добавить музыкальный файл</h2>
    <section class="u-clearfix u-section-1" id="carousel_34a0">

        <div class="u-clearfix u-sheet u-sheet-1">
            <div class="u-expanded-width-lg u-expanded-width-sm u-shape u-shape-svg u-text-palette-1-light-1 u-shape-1">
                <svg class="u-svg-link" preserveAspectRatio="none" viewBox="0 0 160 150" style=""><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-1073"></use></svg>
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" xml:space="preserve" class="u-svg-content" viewBox="0 0 160 150" x="0px" y="0px" id="svg-1073"><path d="M43.2,126.9c14.2,1.3,27.6,7,39.1,15.6c8.3,6.1,19.4,10.3,32.7,5.3c11.7-4.4,18.6-17.4,21-30.2c2.6-13.3,8.1-25.9,15.7-37.1
	c8.3-12.1,10.8-27.9,5.3-42.7C150.5,20.3,134.6,9,117,7.6C107.9,6.9,98.8,5,90.1,1.9C83-0.6,75-0.7,67.4,2.1
	c-9.9,3.7-17,11.6-20.1,21c-3.3,10.1-10.9,18-20.6,22.2c-0.1,0-0.1,0.1-0.2,0.1c-20.3,8.9-31,32-24.6,53.2
	C6.9,115.6,25.2,125.2,43.2,126.9z"></path></svg>
            </div>
            <div class="u-align-left u-image u-image-circle u-preserve-proportions u-image-1" data-image-width="616" data-image-height="616"></div>
            <div class="u-palette-1-light-2 u-shape u-shape-circle u-shape-2"></div>
            <div class="u-form u-radius-31 u-white u-form-1 editCrard--padding editCard--shadow ">

                <form action="#" method="POST" class="u-clearfix u-form-spacing-33 u-form-vertical u-inner-form" source="email" name="form" style="padding: 35px;">

                    <div class="u-form-group u-form-name">
                        <label for="name-4c18" class="u-label">Название</label>
                        @Html.EditorFor(model => model.Name_music, new { htmlAttributes = new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10", placeholder = "Введите название", type = "text" } })
                        @Html.ValidationMessageFor(model => model.Name_music, "", new { @class = "text-danger" })

                    </div>
                    <div class="u-form-group">
                        <label for="message-4c18" class="u-label">Описание</label>
                        @Html.EditorFor(model => model.Description_Music, new { htmlAttributes = new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10", placeholder = "Введите описание" } })
                        @Html.ValidationMessageFor(model => model.Description_Music, "", new { @class = "text-danger" })

                    </div>
                    <div class="u-form-group">
                        <label for="name-4c18" class="u-label">Цена</label>
                        @Html.EditorFor(model => model.PriceString, new { htmlAttributes = new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10", placeholder = "Введите цену" } })
                        @Html.ValidationMessageFor(model => model.PriceString, "", new { @class = "text-danger" })

                    </div>

                    <div class="u-form-group u-form-group-4">
                        <label for="text-7110" class="u-label">Тип музыки</label>
                        @Html.DropDownList("ID_Type_mysic", null, htmlAttributes: new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10" })
                        @Html.ValidationMessageFor(model => model.ID_Type_mysic, "", new { @class = "text-danger" })

                    </div>
                    <div class="u-form-group u-form-group-5">
                        <label for="text-ce90" class="u-label">Жанр</label>
                        @Html.DropDownList("ID_Genere_of_Music", null, htmlAttributes: new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10" })
                        @Html.ValidationMessageFor(model => model.ID_Genere_of_Music, "", new { @class = "text-danger" })

                    </div>

                    <div class="u-form-group u-form-group-5">
                        <label for="text-ce90" class="u-label">Альбом</label>
                        @Html.DropDownList("ID_Alboms",  null, htmlAttributes: new { @class = "form-control u-border-2 u-border-palette-1-light-2 u-input u-input-rectangle u-palette-1-light-3 u-radius-10" })
                        @Html.ValidationMessageFor(model => model.ID_Alboms, "", new { @class = "text-danger" })

                    </div>


                    <label for="text-1f9b" class="u-label">Фото</label>
                    <div class="form-group editCard--margin">

                        <div class="col-md-10 editCard_DivImage--margin">


                            @Html.ValidationMessageFor(model => model.Image_music, "", new { @class = "text-danger" })


                        </div>
                        <div class="editCard--margin">
                            <input id="musicInput" type="file" name="uploadImage" />
                        </div>
                    </div>



                    <label for="text-1f9b" class="u-label">Музыкальный файл</label>
                    <div class="form-group editCard--margin">

                        <div class="col-md-10 editCard_DivImage--margin">

                            @*@Html.Raw("<img id='previewImage' style='width:130px; height:120px;' src=\"data:image/jpeg;base64,"
                + Convert.ToBase64String(Model.Image_music) + "\" />")*@


                            @Html.ValidationMessageFor(model => model.Music_file, "", new { @class = "text-danger" })


                        </div>

                        <div class="editCard--margin">
                            <input id="musicInput" type="file" name="uploadMusic" />
                        </div>
                    </div>
                    <div class=" col-xs-12 checkbox">
                        <label>
                            @Html.CheckBoxFor(model => model.IsLicenseAgreementAccepted,
                                           new
                                           {
                                               htmlAttributes = new
                                                    {

                                                       @class = "form-control",
                                                        type = "checkbox",
                                                        id = "blankCheckbox",
                                                    }
                                           })
                            <label>Согласны ли вы с условиями пользовательского соглашения?</label>
                        </label>
                        @Html.ValidationMessageFor(model => model.IsLicenseAgreementAccepted, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group u-align-center u-form-group u-form-submit">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Сохранить" class="btn btn btn-primary editCard_button_size" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
}

<div>
    @Html.ActionLink("Вернуться к личному кабинету", "Users.Details", @class: "header-style-text")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeatLab/Views/Musics/Delete.cshtml
@model BeatLab.Models.Entities.Music

@{
    ViewBag.Title = "Удаление музыки";
}


<h3>Вы точно хотите удалить эту музыку?</h3>
<div>

    <hr />
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Удалить" class="btn btn-default" /> |
    @Html.ActionLink("Вернуться", "Users.Details","", @class: "header-style-text")

</div>
    }
</div>

BeatLab/Views/Musics/Details.cshtml
@model BeatLab.Models.Entities.Music


@{
    ViewBag.Title = "О товаре";

}

<br />


<div class="container">
    <div id="main">


        <div class="row" id="real-estates-detail">
            <div class="col-lg-4 col-md-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <header class="panel-title">
                            <div class="text-center">
                                <strong>Товар</strong>
                            </div>
                        </header>
                    </div>
                    <div class="panel-body" style=" overflow: hidden;">
                        <div class="text-center" id="author">



                            @{ if (Model.Image_music == null)
                                {
                                    <img id='previewImage' class="img_cardDetalies " src="~/Resource/user.png" />
                                }
                                else
                                {
                                    @Html.Raw("<img id='previewImage' class='img_cardDetalies'   src=\"data:image/jpeg;base64,"
                                              + Convert.ToBase64String(Model.Image_music) + "\" />")

                                }
                            }

                            <h3>@Html.DisplayFor(model => model.Name_music)</h3>
                            <small class="label label-warning"> Жанр: @Html.DisplayFor(model => model.Genere_Of_Music.Name_Gener_of_music)</small>
                            <br />
                            <br />
                            <p>@Html.DisplayFor(model => model.Description_Music)</p>
                            <p class="sosmed-author">
                                Цена: @(Model.Price_Music.ToList().Last().Price) руб.
                            </p>
                            <audio controls controlsList="nodownload" oncontextmenu="return false;" id="player">
                                <source src="@Url.Action("LoadAudio", "Musics", new { musicId = Model.ID_Music })" type="audio/mp3" />
                            </audio>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-8 col-xs-12">
                <div class="panel">
                    <div class="panel-body">
                        <ul id="myTab" class="nav nav-pills">
                            <li>

                              
                                @Html.ActionLink(@"Купить", "Create", "Order_Music", new { Model.ID_Music }, new { @class = "" })

                            </li>
                           
                            <li class="">
                                @Html.ActionLink(linkText: "График изменения цен", actionName: "Index", controllerName: "MusicPriceChart", routeValues: new { id = Model.ID_Music }, htmlAttributes: null)
                            </li>

                            <li class="">@Html.ActionLink("Написать сообщение", "Index", "Chat", new { inputReceiverId = Model.ID_User }, null)</li>
                        </ul>

                        <div class="row">

                            <div class="col-md-12">
                                <div class="panel">
                                    <div class="panel-body">
                                        @using (Html.BeginForm("PostComment", "Musics", new { musicId = Model.ID_Music }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                                        {
                                            <textarea name="comment" class="form-control" rows="2" placeholder="Добавьте Ваш комментарий"></textarea>
                                            <div class="mar-top clearfix">
                                                <button class="btn btn-sm btn-primary pull-right" type="submit"><i class="fa fa-pencil fa-fw"></i> Добавить</button>
                                            </div>
                                        }
                                    </div>
                                </div>
                                <div class="panel">
                                    <div class="panel-body">

                                        @foreach (var item in Model.Comment_Music)
                                        {
                                            <div class="media-block">
                                                <a class="media-left" href="#">
                                                    @{ if (item.User.Image_User == null)
                                                        {
                                                            <img id='previewImage' class="img-circle img-sm" alt="Профиль пользователя" src="~/Resource/user.png" />
                                                        }
                                                        else
                                                        {
                                                            @Html.Raw("<img id='previewImage' class='img-circle img-sm'  alt='Профиль пользователя' src=\"data:image/jpeg;base64,"
                                                                                                 + Convert.ToBase64String(item.User.Image_User) + "\" />")

                                                        }
                                                    }

                                                </a>
                                                <div class="media-body">
                                                    <div class="mar-btm">
                                                        <a href="#" class="btn-link text-semibold media-heading box-inline"> @(item.User.Nickname_User)</a>
                                                        <p class="text-muted text-sm"><i class="fa fa-globe fa-lg"></i> - @(item.Data_Comments.Day).@(item.Data_Comments.Month).@(item.Data_Comments.Year)</p>
                                                    </div>
                                                    <p>@(item.Content_Comments)</p>

                                                    <hr>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function play() {
        var audio = document.querySelector(".adu");
        audio.play();
    }
    for (const player of Array.from(document.querySelectorAll('audio'))) {
        player.addEventListener('play', onPlayListener);
    }


    function onPlayListener(event) {
        console.log(event);



        document.querySelector('.track-artist__name').innerHTML = event.target.parentElement.parentElement.querySelector('.nameartistforlayer ').textContent.trim().slice(2);
        document.querySelector('.track-descr__name').innerHTML = event.target.parentElement.parentElement.querySelector('.namesongforplayer ').textContent.trim();
        document.querySelector('.track-descr__style').innerHTML = event.target.parentElement.parentElement.querySelector('.nameagenereforsong ').textContent.trim();
        document.querySelector('.track-descr__cover-img').src = event.target.parentElement.querySelector('img').src;
        event.preventDefault();
        event.target.pause();
        document.getElementById('container-id').hidden = false;
        const audio = event.target;
        const audioClone = audio.cloneNode(true);
        audioClone.muted = false;
        audioClone.removeEventListener('play', onPlayListener);
        audioClone.play();
        const audioContainer = document.querySelector('.player__controls-box');
        audioContainer.removeChild(audioContainer.firstChild);
        audioContainer.appendChild(audioClone);
    }
</script>